name: prm393_backend
description: Dart backend scaffold for PRM393.
publish_to: none
version: 0.1.0
environment:
  sdk: ^3.12.2
dependencies:
  dotenv: ^4.2.0
  shelf: ^1.4.2
dev_dependencies:
  lints: ^6.0.0
